### ISSUE TITLE
About unhook opportunity

### ISSUE THREAD

**Issue by dkzone000** [IronManMark20/pyhooked#27]
Dear ethanhs ,

First , thanks to provide this project .

I have use Console to open the example you provide name "example_gui.py" , 
then if I close the UI , the project still work .
It's mean the threading is not close ? 

Thanks

**Comment by emmatyping** [comment]
Hi @dkzone000, I'm glad you like it! Please be aware that I am not going to support this for much longer (see #25). To answer your question, yes, the thread works separately from the GUI (otherwise it can cause other problems). If you want to exit with the window, you probably want to add the kwarg `daemon=True` to your creation of `Thread`, so that it will end with your GUI. so it would be `threading.Thread(target=hk.hook, daemon=True)` I hope this answers your question.

**Comment by dkzone000** [comment]
Hi @ethanhs  , 

Sorry to post this issue , I found this is python's mechanism , 
then , I will try dameon or subprocess , I think its can solve my problem.

Thanks.

**Comment by emmatyping** [comment]
No problem. daemon should definitely do what you need.
